
project_id = "fxzamjowvpnyuxthusib"

[api]
  enabled = true
  port = 54321
  schemas = ["public", "storage"]

[db]
  port = 54322

[functions]
  [functions.twitter-integration]
    verify_jwt = false
    import_map = "functions/import_map.json"
