
project_id = "fxzamjowvpnyuxthusib"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[storage]
enabled = true

[auth]
enabled = true
site_url = "https://fxzamjowvpnyuxthusib.supabase.co" 
additional_redirect_urls = ["https://fxzamjowvpnyuxthusib.supabase.co", "https://fxzamjowvpnyuxthusib.supabase.co/settings", "https://fxzamjowvpnyuxthusib.supabase.co/functions/v1/twitter-integration/callback", "https://preview--contentory-manager.lovable.app/settings", "https://contentory-manager.lovable.app/settings"]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10
enable_signup = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[auth.external.github]
enabled = true
client_id = "env(SUPABASE_AUTH_GITHUB_CLIENT_ID)"
secret = "env(SUPABASE_AUTH_GITHUB_SECRET)"
redirect_uri = "https://fxzamjowvpnyuxthusib.supabase.co/auth/v1/callback"

[auth.external.google]
enabled = true
client_id = "env(SUPABASE_AUTH_GOOGLE_CLIENT_ID)"
secret = "env(SUPABASE_AUTH_GOOGLE_SECRET)"
redirect_uri = "https://fxzamjowvpnyuxthusib.supabase.co/auth/v1/callback"

[functions]
[functions.twitter-integration]
verify_jwt = false
